# __Preprocesamiento de los datos__

In [8]:
import pandas as pd
import numpy as np

In [9]:
df = pd.read_excel('../data/Afluencia_2021.xlsx')
df.head()

,Fecha,Linea,04:00:00,05:00:00,06:00:00,07:00:00,08:00:00,09:00:00,10:00:00,11:00:00,...,15:00:00,16:00:00,17:00:00,18:00:00,19:00:00,20:00:00,21:00:00,22:00:00,23:00:00,Total general (Número de pasajeros)
0,2021-01-01,LÍNEA A,NaN,3487.0,3405.0,2011.0,1148.0,974.0,888.0,1011.0,...,1833.0,2900.0,3269.0,3314.0,2273.0,1329.0,12.0,NaN,NaN,31911
1,2021-01-01,LÍNEA B,NaN,532.0,438.0,267.0,164.0,145.0,135.0,142.0,...,212.0,321.0,421.0,432.0,215.0,157.0,NaN,NaN,NaN,4050
2,2021-01-01,LÍNEA K,NaN,NaN,NaN,NaN,40.0,131.0,104.0,156.0,...,167.0,258.0,189.0,122.0,103.0,38.0,NaN,NaN,NaN,1714
3,2021-01-01,LÍNEA J,NaN,NaN,NaN,NaN,1.0,77.0,74.0,92.0,...,146.0,179.0,132.0,135.0,69.0,42.0,3.0,NaN,NaN,1256
4,2021-01-01,LÍNEA 1,NaN,614.0,590.0,355.0,240.0,217.0,198.0,231.0,...,394.0,579.0,624.0,574.0,399.0,231.0,17.0,NaN,NaN,6104

In [10]:
df22 =pd.read_excel('../data/Afluencia_2022.xlsx')
df22.head()

,Fecha,Linea,04:00:00,05:00:00,06:00:00,07:00:00,08:00:00,09:00:00,10:00:00,11:00:00,...,15:00:00,16:00:00,17:00:00,18:00:00,19:00:00,20:00:00,21:00:00,22:00:00,23:00:00,Total general (Número de pasajeros)
0,2022-01-01,LÍNEA 1,165.0,811.0,854.0,662.0,589.0,731.0,836.0,1091.0,...,1479.0,1616.0,1696.0,1911.0,1611.0,1319.0,923.0,132.0,NaN,20279
1,2022-01-01,LÍNEA 2,14.0,90.0,100.0,81.0,68.0,95.0,93.0,90.0,...,168.0,212.0,213.0,222.0,169.0,118.0,71.0,8.0,NaN,2265
2,2022-01-01,LÍNEA A,1098.0,4363.0,5114.0,3988.0,3385.0,4033.0,4890.0,6163.0,...,9089.0,10642.0,11322.0,12716.0,10610.0,8085.0,6333.0,476.0,NaN,126692
3,2022-01-01,LÍNEA B,195.0,674.0,767.0,555.0,565.0,667.0,921.0,1246.0,...,1599.0,2121.0,2114.0,2204.0,1526.0,1028.0,620.0,58.0,NaN,21301
4,2022-01-01,LÍNEA H,NaN,NaN,NaN,NaN,NaN,39.0,25.0,45.0,...,44.0,37.0,71.0,80.0,61.0,42.0,14.0,NaN,NaN,641